### ISSUE TITLE
Discussion: Desire for collaboration, the needs of LCLS

### ISSUE THREAD

**Issue by klauer** [NSLS-II/bluesky-widgets-demo#14]
Background
-------------

At the LCLS, we now have a need for a simple scanning GUI, on the timescale of roughly mid May.

While our requirements are minimal, it was decided rather than make a one-off solution that we might have to maintain for an eternity, we should instead aid the collaboration in reaching their deadline and mutually benefit.

A [test facility](https://lcls.slac.stanford.edu/instruments/mev-ued) at LCLS previously had a GUI that relied on the step scan record. We'd like to move it to [hutch-python](https://github.com/pcdshub/hutch-python/), bluesky, ophyd, and PyDM/typhos/lucid/bluesky-widgets on top.

Their old GUI
--------------

<img width="774" alt="image" src="https://user-images.githubusercontent.com/5139267/114758835-43f47b00-9d12-11eb-8fa2-a1e4367f25de.png">

As you can see on the top left, the scan parameters - and thus the scan itself - required are rather simple.

LCLS's requirements
----------------------

Our requirements are barebones for starters.

At bare minimum:
* Run an arbitrary plan, passing in arguments as necessary (for now, built-in 1D scans would suffice I believe)
* The usual queue control options, e.g., stop/pause/abort a plan
* Maybe special: repeat a plan forever (until canceled) automatically
* We'd like to mix in PyDM widgets to be able to interface with other motor controls to effectively replace the other ancient EDM functionality above.

Those involved
---------------

@cristinasewell - part of our TID department, matrixed to PCDS, frequent contributor to PCDS libraries, and person who will likely help NSLS-II mostly here
@ZLLentz - head of UI/UX for LCLS, who may contribute
@klauer - interested party who gets in the way of things and may also contribute here

Questions / Path forward
-------------

* Am I missing any of our requirements here, @zllentz @cristinasewell?
* What can we do to effectively help move this effort forward?
* Can we contribute anything today? Should we wait?

**Comment by danielballan** [comment]
It's always a pleasure to collaborate with @ZLLentz and to stumble over @klauer when he gets in the way. :-D @cristinasewell, we look forward to working with you!

## Where to start now

The main difference between this effort and all known previous efforts toward driving the RunEngine from a GUI is that in our case the RunEngine runs of in a "worker" (a nanny process) that takes instructions via a custom 0MQ-based communication band. This means that the GUI can disconnect and reconnect from the RunEngine without disrupting its operation.

1. Can you get `start-re-manager` working on your machine? I think @klauer may have already tried this. If you just start it as `start-re-manager` with no arguments it runs in a demo mode. See the [README in bluesky-queueserver](https://github.com/bluesky/bluesky-queueserver) for more.
2. Can you get `start-re-manager` connected to your ophyd devices? See the various options named `--startup-*` in `start-re-manager --help`.

## Features that you could potentially work on

* I do not think we have a way of saying "Repeat this plan forever in the queue." You could work on that. Off the top of my head this could be done in the GUI layer or added to the vocabulary of the queue itself, akin to a "repeat track" mode in a music playlist queue. attn @dmgav 
* I am not sure how far @dmgav is going with input forms for plan parameters. You could potentially work with him on that if there is a good collaboration point. Again, attn @dmgav.

Let's find some time for us to give you a quick tour of things --- in particular the MVVM architecture and communication pathways --- in the next couple days.

Do you have any particular visualization needs?

**Comment by dmgav** [comment]
I am planning to implement basic 'universal' widget to input plan parameters. But 'plan editor' will be a separate widget, which is easy to replace with custom widget. I don't think any universal plan editing widget may cover all user cases.

**Comment by klauer** [comment]
Looks like this issue ended up being nigh useless - oh well. Shall we close it?
